# Fichier de configuration pour Netlify

[build]
  # Commande pour construire le site Next.js
  command = "next build"
  
  # Répertoire où se trouve le site construit
  publish = ".next"

# Ce plugin est essentiel pour que Netlify comprenne comment gérer
# les redirections, les pages statiques et les fonctions serveur de Next.js.
[[plugins]]
  package = "@netlify/plugin-nextjs"
